language: php

matrix:
  exclude:
    - env: MOCKERY_VERSION=1.4.*
      php: 7.1
    - env: MOCKERY_VERSION=1.4.*
      php: 7.2
    - env: MOCKERY_VERSION=1.4.*
      php: 7.3

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

env:
  - MOCKERY_VERSION=1.0.*
  - MOCKERY_VERSION=1.1.*
  - MOCKERY_VERSION=1.2.*
  - MOCKERY_VERSION=1.3.*
  - MOCKERY_VERSION=1.4.*

before_script:
  - composer self-update
  - |
    if php -r 'exit((int)!version_compare(getenv("TRAVIS_PHP_VERSION"), "7.2", "<"));'; then
      composer require "phpunit/phpunit:^7.0" "mockery/mockery:${MOCKERY_VERSION}" --no-update
    elif php -r 'exit((int)!version_compare(getenv("TRAVIS_PHP_VERSION"), "7.3", "<"));'; then
      composer require "phpunit/phpunit:^8.0" "mockery/mockery:${MOCKERY_VERSION}" --no-update
    else
      composer require "mockery/mockery:${MOCKERY_VERSION}" --no-update
    fi
  - composer update
  - mkdir -p build/logs

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
