name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4, 8.0]
        mockery: ['1.0.*', '1.1.*', '1.2.*', '1.3.*', '1.4.*']
        exclude:
          - php: 7.1
            mockery: '1.4.*'
          - php: 7.2
            mockery: '1.4.*'
          - php: 7.3
            mockery: '1.4.*'

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - run: |
          if php -r 'exit((int)!version_compare(PHP_VERSION, "7.2", "<"));'; then
            composer require "phpunit/phpunit:^7.0" "mockery/mockery:${{ matrix.mockery }}" --no-update
          elif php -r 'exit((int)!version_compare(PHP_VERSION, "7.3", "<"));'; then
            composer require "phpunit/phpunit:^8.0" "mockery/mockery:${{ matrix.mockery }}" --no-update
          else
            composer require "mockery/mockery:${{ matrix.mockery }}" --no-update
          fi
      - run: composer update
      - run: mkdir -p build/logs
      - run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Upload Coverage
        uses: nick-invision/retry@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: |
            composer global require php-coveralls/php-coveralls
            php-coveralls --coverage_clover=build/logs/clover.xml -v
